services:
  jenkins-app:
    container_name: jenkins_app
    build: jenkins/.
    ports:
      - 8080:8080
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 4G
        reservations:
          cpus: "0.1"
          memory: 512M
    volumes:
      - jenkins_volume:/var/jenkins_home

volumes:
  jenkins_volume: