services:
  docker-dind-server:
    container_name: docker_dind_for_jenkins
    image: docker:dind
    privileged: true
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    ports:
      - 2376:2376
    volumes:
      - jenkins_docker_certs:/certs/client
      - jenkins_volume:/var/jenkins_home
    networks:
      jenkins:
        aliases:
        - docker

  jenkins-app:
    container_name: jenkins_app
    build: jenkins/.
    environment:
      - DOCKER_TLS_VERIFY=1
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_HOST=tcp://docker:2376
    networks:
      - jenkins
    ports:
      - 8080:8080
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 4G
        reservations:
          cpus: "0.1"
          memory: 512M
    volumes:
      - jenkins_volume:/var/jenkins_home
      - jenkins_docker_certs:/certs/client:ro 
    depends_on:
      - docker-dind-server

networks:
  jenkins:

volumes:
  jenkins_volume:
  jenkins_docker_certs: