services:
  jenkins-node:
    container_name: jenkins-node-only
    build: .
    ports:
      - 8080:8080
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 4G
        reservations:
          cpus: "0.1"
          memory: 512M
    volumes:
      - jenkins-node-vol:/var/jenkins_home

  ngrok-bypass:
    container_name: ngrok-bypass
    image: ngrok/ngrok:latest 
    restart: unless-stopped
    command:
      - "http"
      - "--url=${NGROK_STATIC_URL}"
      - "http://jenkins-node:8080"
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    ports:
      - 4040:4040

volumes:
  jenkins-node-vol: